# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
        - image: circleci/buildpack-deps:latest
    steps:
      - checkout

      - setup_remote_docker

      - run: make

      - run: sleep 5 && curl -sSf http://localhost:8080/margin_stocks
